config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  controller :rights do
    get "terms"  => :terms
    get "cookie" => :cookie
    get "gdpr"   => :gdpr
  end

  controller :sessions do
    get    "login"  => :new
    post   "login"  => :create
    delete "logout" => :destroy
  end
  resources :passwords, param: :token, except: %i[ index show destroy ]

  shallow do
    resources :users, except: %i[index show] do
      resources :searches, except: %i[index edit update]
      resources :analytics, only: [ :index ]
    end
  end

  shallow do
    resources :accounts, except: [ :show ] do
      resources :categories, except: [ :show ] do
        post "import_from", on: :collection
      end
      resources :transactions, except: [ :show ] do
        post "easycheck", on: :member
      end
      resources :schedules, except: [ :show ] do
        post "insert", on: :member
      end
    end
  end

  delete "accounts/:id/unlink(.:format)",    to: "accounts#unlink",    as: "unlink"
  delete "accounts/:id/unpend(.:format)",    to: "accounts#unpend",    as: "unpend"
  post   "accounts/:id/sharing(.:format)",   to: "accounts#sharing",   as: "sharing"
  delete "accounts/:id/unsharing(.:format)", to: "accounts#unsharing", as: "unsharing"

  root "dashboard#index", as: "dashboard"
end

app/models/schedule.rb
# == Schema Information
#
# Table name: schedules
#
#  id         :integer          not null, primary key
#  created_by :integer
#  frequency  :integer          not null
#  next_time  :date             not null
#  period     :string           not null
#  updated_by :integer
#  created_at :datetime
#  updated_at :datetime
#  account_id :integer          not null
#
# Indexes
#
#  index_schedules_on_account_id  (account_id)
#  index_schedules_on_created_by  (created_by)
#  index_schedules_on_updated_by  (updated_by)
#
# Foreign Keys
#
#  account_id  (account_id => accounts.id)
#  created_by  (created_by => users.id)
#  updated_by  (updated_by => users.id)
#

class Schedule < ApplicationRecord
  has_one :operation, class_name: "Transaction", dependent: :destroy, inverse_of: :schedule
  accepts_nested_attributes_for :operation, update_only: true, allow_destroy: true
  belongs_to :account

  scope :order_by_next_time_and_id, -> { order(next_time: :asc, id: :asc) }

  validates :next_time,  presence:     true
  validates :frequency,  presence:     true
  validates :period,     presence:     true
  validates :operation,  presence:     true
  validates :frequency,  numericality: true

  before_validation :populate_date

  private

    def populate_date
      return if next_time.nil? || operation.nil?

      operation.date = next_time
      operation.save
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  include DashboardData
  before_action :set_current_account

  # GET /accounts/:account_id/schedules
  def index
    load_limit

    respond_to do |format|
      format.html do
        @nb_schedules = current_schedules.count
        schedules(limit: @limit)
        @all_user_schedules = Schedule.where(account: @current_accounts)
      end
      format.turbo_stream do
        @nb_schedules = current_schedules.count
        @nb_items = params[:offset].to_i.abs + @limit
        schedules(offset: params[:offset].to_i.abs, limit: @limit)
      end
      format.xlsx do
        attributes_to_extract = %w[id account_id next_time frequency period]
        send_data current_schedules.to_xlsx(attributes_to_extract, "schedules"),
                  filename: "#{I18n.t("schedules.new.schedules")}_#{timestamp_for_export}.xlsx",
                  type:     :xlsx
      end
    end
  end

  # GET /accounts/:account_id/schedules/new
  def new
    build_schedule
    @schedule.build_operation
    @sign = "debit"
  end

  # GET /schedules/:id/edit
  def edit
    schedule

    @sign = @schedule.operation.amount.negative? ? "debit" : "credit"
    @schedule.operation.amount = @schedule.operation.amount.abs
  end

  # POST /accounts/:account_id/schedules
  def create
    build_schedule

    # TODO: could be refactored with update?
    @schedule.account = @current_account
    @schedule.operation.account = @current_account

    if save_schedule
      redirect_to account_schedules_url(@current_account), notice: t(".successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /schedules/:id
  def update
    schedule
    build_schedule

    # TODO: could be refactored with create?
    @schedule.account = @current_account
    @schedule.operation.account = @current_account

    if save_schedule
      redirect_to account_schedules_url(@current_account), notice: t(".successfully_updated"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /schedules/:id
  def destroy
    schedule
    if @schedule.destroy
      respond_to do |format|
        format.html { redirect_to account_schedules_url(@current_account), notice: t(".successfully_destroyed") }
        format.turbo_stream do
          @successful_destroy = true
          @nb_schedules = current_schedules.count
          flash.now[:notice] = t(".successfully_destroyed")
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to account_schedules_url(@current_account), warning: t(".cant_destroy") }
        format.turbo_stream do
          @successful_destroy = false
          flash.now[:warning] = t(".cant_destroy")
        end
      end
    end
  end

  # POST /schedules/:id/insert
  def insert
    schedule

    transaction = @schedule.operation.dup
    transaction.schedule_id = nil
    userstamp(transaction)
    transaction.created_by = @current_user.id

    @schedule.next_time = @schedule.next_time.advance(@schedule.period.to_sym => @schedule.frequency)
    userstamp(@schedule)

    transaction.save
    @schedule.save

    begin
      respond_to do |format|
        format.html { redirect_to dashboard_url, notice: t(".successfully_inserted"), status: :see_other }
        format.turbo_stream do
          load_transactions
          load_current_transactions
          if params[:origin] == "dashboard"
            load_schedules
          else
            schedules
            flash.now[:notice] = t(".successfully_inserted")
          end
        end
      end
    rescue StandardError
      redirect_to dashboard_url, notice: t(".successfully_inserted")
    end
  end

  private ##############################################################################################################

    def schedules(options = {})
      @schedules ||= current_schedules.offset(options[:offset]).limit(options[:limit]).order_by_next_time_and_id
    end

    def schedule
      @schedule ||= current_schedules.find(params[:id])
    end

    def build_schedule
      @schedule ||= current_schedules.build
      @schedule.attributes = schedule_params
    end

    def schedule_params
      schedule_params = params[:schedule]
      if schedule_params
        schedule_params.permit(:next_time,
                               :frequency,
                               :period,
                               operation_attributes: %i[amount category_id comment checked])
      else
        {}
      end
    end

    def save_schedule
      return unless @schedule.save

      if params[:sign] == "credit"
        @schedule.operation.amount = @schedule.operation.amount.abs if @schedule.operation.amount.present?
      elsif @schedule.operation.amount.present?
        @schedule.operation.amount = @schedule.operation.amount.abs * -1
        @schedule.operation.save
      end

      userstamp(@schedule)
    end

    def current_schedules
      @current_account.schedules
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def easy_t(period)
    case period
    when "days"   then t(".days")
    when "weeks"  then t(".weeks")
    when "months" then t(".months")
    when "years"  then t(".years")
    end
  end
end

app/views/schedules/_form.html.erb
<%= form_with(model: shallow_args(@current_account, @schedule), class: "box", data: { turbo: false }) do |form| %>
  <div class="content has-text-centered">
    <%= icon_text("fa-regular fa-calendar-days", title) %>
    <hr />
  </div>

  <%= form.fields_for :operation do |operation_fields| %>
    <%= render "operation_form", form: operation_fields %>
  <% end %>

  <hr />

  <%# frequency %>
  <div class="field">
    <%= form.label :frequency, t(".frequency"), class: "label" %>
    <div class="field has-addons">
      <div class="control">
        <div class="button is-static">
          <%= t(".all_the") %>
        </div>
      </div>
      <div class="control">
        <%= form.number_field :frequency, class: input_class_for(@schedule, :frequency), placeholder: t(".frequency") %>
        <% @schedule.errors.full_messages_for(:frequency).each do |message| %>
          <p class="help is-danger">
            <%= message %>
          </p>
        <% end %>
      </div>
      <div class="control">
        <span class="select">
          <%= form.select :period, [[t(".days"), :days], [t(".weeks"), :weeks], [t(".months"), :months], [t(".years"), :years]], {} %>
          <% @schedule.errors.full_messages_for(:period).each do |message| %>
            <p class="help is-danger">
              <%= message %>
            </p>
          <% end %>
        </span>
      </div>
    </div>
  </div>

  <%# next time %>
  <div class="field">
    <%= form.label :next_time, t(".next_time"), class: "label" %>
    <div class="control has-icons-left">
      <%= form.date_field :next_time,
                          class: input_class_for(@schedule, :next_time), \
                          placeholder: t(".next_time"), \
                          value: @schedule.next_time.nil? ? Date.today : @schedule.next_time %>
      <span class="icon is-left">
        <%= icon("fa-regular fa-calendar-days") %>
      </span>
      <% @schedule.errors.full_messages_for(:next_time).each do |message| %>
        <p class="help is-danger">
          <%= message %>
        </p>
      <% end %>
    </div>
  </div>

  <%# submit button %>
  <div class="mt-5">
    <%= form.submit class: "button is-success is-fullwidth" %>
  </div>
<% end %>

app/views/schedules/_operation_form.html.erb
<%# amount %>
<div class="field">
  <%= form.label :amount, t(".amount"), class: "label" %>
  <div class="field has-addons">
    <div class="control">
      <div class="select">
        <%= select_tag :sign, options_for_select([[t(".debit"), "debit"], [t(".credit"), "credit"]], @sign) %>
      </div>
    </div>
    <div class="control is-expanded has-icons-right">
      <%= form.number_field :amount, class: input_class_for(@schedule.operation, :amount), placeholder: t(".amount"), autofocus: true, step: 0.01 %>
      <span class="icon is-right">
        <%= t("number.currency.format.unit") %>
      </span>
      <% @schedule.operation.errors.full_messages_for(:amount).each do |message| %>
        <p class="help is-danger">
          <%= message %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<%# category %>
<div class="field">
  <%= form.label :category_id, t(".category"), class: "label" %>
  <div class="control is-expanded has-icons-left">
    <div class="select is-fullwidth">
      <%= form.select :category_id, @current_account.categories.active.order(:name).collect { |category| [category.name, category.id] } %>
    </div>
    <span class="icon is-left">
      <%= icon("fa-solid fa-tags") %>
    </span>
  </div>
</div>

<%# comment %>
<div class="field">
  <%= form.label :comment, t(".comment"), class: "label" %>
  <div class="control">
    <%= form.text_area :comment, class: "textarea", placeholder: t(".comment"), rows: 3 %>
  </div>
</div>

<%# checked %>
<div class="field">
  <%= form.label :checked, t(".checked"), class: "checkbox" do %>
    <%= form.check_box :checked %>
    <%= " " + t(".checked") %>
  <% end %>
</div>

app/views/schedules/_schedule.html.erb
<% schedules.each do |schedule| %>
  <tr id="<%= dom_id(schedule) %>">
    <%# magic wand %>
    <td>
      <%= link_to icon("fa-solid fa-wand-magic"),
                  insert_schedule_path(schedule),
                  method: :post,
                  data: { turbo_method: :post },
                  title: t(".insert_schedule"),
                  class: "link-success" %>
    </td>

    <%# next_time %>
    <td data-title="<%= next_time %>">
      <%= l(schedule.next_time) %>
    </td>

    <%# frequency %>
    <td data-title="<%= frequency %>">
      <%= t(".frequency_period", frequency: schedule.frequency.to_s, period: easy_t(schedule.period)) %>
    </td>

    <%# category %>
    <td data-title="<%= category %>">
      <%= schedule.operation.category.name %>
    </td>

    <%# amount %>
    <td class="nowrap" data-title="<%= amount %>" style="text-align: right;">
      <%= number_to_currency(schedule.operation.amount) %>
    </td>

    <%# comment %>
    <td data-title="<%= comment %>">
      <%= truncate(schedule.operation.comment, length: 30) %>
    </td>

    <%# common %>
    <td>
      <div class="level is-mobile">
        <div class="level-left">
          <div class="level-item has-text-centered">
            <%= link_to icon("fa-solid fa-pen-to-square"), edit_schedule_path(schedule), title: t(".edit"), class: "has-text-info" %>
          </div>
          <div class="level-item has-text-centered">
            <%= link_to icon("fa-regular fa-trash-can"),
                        schedule_path(schedule),
                        data: { turbo_method: :delete, turbo_confirm: t(".are_you_sure") },
                        title: t(".destroy"),
                        class: "has-text-danger" %>
          </div>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/schedules/_transaction_fields.html.slim
.form-group
  = f.label :amount, t('.amount'), class: "col-sm-2 control-label"
  .col-sm-2
    = select_tag :sign, options_for_select( [ \
        [t('.debit'), "debit"], [t('.credit'), "credit"] ], @sign), \
        { class: "form-control" }
  .col-sm-2
    .input-group
      = f.text_field :amount, class: "form-control", placeholder: t('.amount'), autofocus: true
      span.input-group-addon = t('number.currency.format.unit')

.form-group
  = f.label :category_id, t('.category'), class: "col-sm-2 control-label"
  .col-sm-4
    = f.select :category_id, @current_account.categories.order(:name ).collect { |category| \
                  [ category.name, category.id ] }, {}, { class: "form-control" }

.form-group
  = f.label :comment, t('.comment'), class: "col-sm-2 control-label"
  .col-sm-4
    = f.text_area :comment, class: "form-control", placeholder: t('.comment'), rows: 5

.form-group
  .col-sm-offset-2.col-sm-2
    .checkbox
      = f.label :checked do
        = f.check_box :checked
        = t('.checked')

app/views/schedules/_welcome.html.erb
<div class="modal is-active" data-action="keydown.esc@window->layout#hideModal" data-controller="layout" data-layout-target="modal">
  <div class="modal-background">
  </div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title is-size-6-mobile">
        <%= t(".welcome") %>
      </p>
      <button class="delete" data-action="layout#hideModal"></button>
    </header>
    <section class="modal-card-body">
      <div class="content">
        <%= t(".content", new_icon: icon("fa-solid fa-circle-plus"), magic_icon: icon("fa-solid fa-wand-magic")).html_safe %>
      </div>
    </section>
    <footer class="modal-card-foot">
      <button class="button is-success" data-action="layout#hideModal">
        <%= t(".close") %>
      </button>
    </footer>
  </div>
</div>

app/views/schedules/destroy.turbo_stream.erb
<% if @successful_destroy %>
  <%# remove item in table %>
  <%= turbo_stream.remove @schedule %>

  <%# update total number of items %>
  <%= turbo_stream.replace "total", partial: "layouts/tag", locals: { title: t(".count"), number_of: @nb_schedules } %>
<% end %>

<%# show flash message %>
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/schedules/edit.html.erb
<%= breadcrumb link_to(@current_account.name, account_schedules_path(@current_account)),
               link_to(t(".edit_schedule"), edit_schedule_path(@schedule)) %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".edit_schedule") } %>
  </div>
</div>

app/views/schedules/index.html.erb
<%# welcome %>
<% unless @all_user_schedules.any? %>
  <%= render "welcome" %>
<% end %>

<%# header %>
<div class="level">
  <%# title %>
  <div class="level-left">
    <div class="level-item">
      <h2 class="title">
        <%= t(".listing_schedules", current_account: @current_account.name) %>
        <%= render partial: "layouts/tag", locals: { title: t('.count'), number_of: @nb_schedules } %>
      </h2>
    </div>
  </div>

  <div class="level-right">
    <%# download %>
    <div class="level-item is-hidden-touch">
      <%= link_to icon("fa-solid fa-download"),
                  account_schedules_path(@current_account, format: :xlsx),
                  title: t(".export_schedules"),
                  class: "button is-link is-light" %>
    </div>
    <%# new schedule %>
    <div class="level-item">
      <%= link_to icon_text("fa-solid fa-circle-plus", t(".new_schedule")), new_account_schedule_path, class: "button is-primary" %>
    </div>
  </div>
</div>

<%# table %>
<table class="table is-fullwidth is-striped" id="magic-table">
  <thead>
    <tr>
      <th></th>
      <th>
        <%= t(".next_time") %>
      </th>
      <th>
        <%= t(".frequency") %>
      </th>
      <th>
        <%= t(".category") %>
      </th>
      <th class="text-end">
        <%= t(".amount") %>
      </th>
      <th>
        <%= t(".comment") %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody id="listing">
    <%= render partial: "schedule", locals: { schedules: @schedules,
                                              next_time: t(".next_time"),
                                              frequency: t(".frequency"),
                                              category:  t(".category"),
                                              amount:    t(".amount"),
                                              comment:   t(".comment") } %>
  </tbody>
</table>

<%# more schedules %>
<% if @nb_schedules > @limit %>
  <%= turbo_frame_tag "items", src: account_schedules_path(@current_account, offset: @limit, format: :turbo_stream), loading: "lazy" %>
<% end %>

app/views/schedules/index.turbo_stream.erb
<%= turbo_stream.append "listing", partial: "schedule", locals:  { schedules: @schedules,
                                                                   next_time: t(".next_time"),
                                                                   frequency: t(".frequency"),
                                                                   category:  t(".category"),
                                                                   amount:    t(".amount"),
                                                                   comment:   t(".comment") } %>

<% if @nb_schedules > @nb_items %>
  <%= turbo_stream.replace "items" do %>
    <%= turbo_frame_tag "items", src: account_schedules_path(@current_account, offset: @nb_items, format: :turbo_stream), loading: "lazy" %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "items" %>
<% end %>

app/views/schedules/insert.turbo_stream.erb
<% if params[:origin] == "dashboard" %>
  <%= turbo_stream.replace "upcoming-terms", partial: "dashboard/upcoming_terms" %>
  <%= turbo_stream.replace "transactions-summary", partial: "dashboard/transactions_summary" %>
<% else %>
  <%= turbo_stream.update "listing", partial: "schedule", locals: { schedules: @schedules,
                                                                    next_time: t(".next_time"),
                                                                    frequency: t(".frequency"),
                                                                    category:  t(".category"),
                                                                    amount:    t(".amount"),
                                                                    comment:   t(".comment") } %>
  <%= turbo_stream.replace "flash", partial: "layouts/flash" %>
<% end %>

app/views/schedules/new.html.erb
<%= breadcrumb link_to(@current_account.name, account_schedules_path(@current_account)),
               link_to(t(".create_schedule"), new_account_schedule_path) %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".create_schedule") } %>
  </div>
</div>