config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  controller :rights do
    get "terms"  => :terms
    get "cookie" => :cookie
    get "gdpr"   => :gdpr
  end

  controller :sessions do
    get    "login"  => :new
    post   "login"  => :create
    delete "logout" => :destroy
  end
  resources :passwords, param: :token, except: %i[ index show destroy ]

  shallow do
    resources :users, except: %i[index show] do
      resources :searches, except: %i[index edit update]
      resources :analytics, only: [ :index ]
    end
  end

  shallow do
    resources :accounts, except: [ :show ] do
      resources :categories, except: [ :show ] do
        post "import_from", on: :collection
      end
      resources :transactions, except: [ :show ] do
        post "easycheck", on: :member
      end
      resources :schedules, except: [ :show ] do
        post "insert", on: :member
      end
    end
  end

  delete "accounts/:id/unlink(.:format)",    to: "accounts#unlink",    as: "unlink"
  delete "accounts/:id/unpend(.:format)",    to: "accounts#unpend",    as: "unpend"
  post   "accounts/:id/sharing(.:format)",   to: "accounts#sharing",   as: "sharing"
  delete "accounts/:id/unsharing(.:format)", to: "accounts#unsharing", as: "unsharing"

  root "dashboard#index", as: "dashboard"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  created_by :integer
#  hidden     :boolean          default(FALSE), not null
#  name       :string           not null
#  updated_by :integer
#  created_at :datetime
#  updated_at :datetime
#  account_id :integer          not null
#
# Indexes
#
#  index_categories_on_account_id           (account_id)
#  index_categories_on_account_id_and_name  (account_id,name) UNIQUE
#  index_categories_on_created_by           (created_by)
#  index_categories_on_updated_by           (updated_by)
#
# Foreign Keys
#
#  account_id  (account_id => accounts.id)
#  created_by  (created_by => users.id)
#  updated_by  (updated_by => users.id)
#

class Category < ApplicationRecord
  belongs_to  :account
  has_many    :transactions, dependent: :restrict_with_error

  has_many :search_targets, as: :target, dependent: :destroy
  has_many :searches, through: :search_targets

  scope :order_by_name, -> { order(name: :asc) }
  scope :active,        -> { where(hidden: false) }

  validates :name, presence: true, uniqueness: { scope: :account_id }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_current_account

  # GET /accounts/:account_id/categories
  def index
    load_limit

    respond_to do |format|
      format.html do
        @nb_categories = current_categories.count
        categories(limit: @limit)
        load_other_accounts
        @all_user_categories = Category.where(account: @current_accounts)
      end
      format.turbo_stream do
        @nb_categories = current_categories.count
        @nb_items = params[:offset].to_i.abs + @limit
        categories(offset: params[:offset].to_i.abs, limit: @limit)
      end
      format.xlsx do
        attributes_to_extract = %w[id account_id name hidden]
        send_data current_categories.to_xlsx(attributes_to_extract, "categories"),
                  filename: "#{I18n.t("categories.new.categories")}_#{timestamp_for_export}.xlsx",
                  type:     :xlsx
      end
    end
  end

  # GET /accounts/:account_id/categories/new
  def new
    build_category
  end

  # GET /categories/:id/edit
  def edit
    category
  end

  # POST /accounts/:account_id/categories
  def create
    build_category
    if save_category
      redirect_to account_categories_url(@current_account), notice: t(".successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /categories/:id
  def update
    category
    build_category
    if save_category
      redirect_to account_categories_url(@current_account), notice: t(".successfully_updated"), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /categories/:id
  def destroy
    category
    if @category.destroy
      respond_to do |format|
        format.html { redirect_to account_categories_url(@current_account), notice: t(".successfully_destroyed") }
        format.turbo_stream do
          @successful_destroy = true
          @nb_categories = current_categories.count
          flash.now[:notice] = t(".successfully_destroyed")
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to account_categories_url(@current_account), warning: t(".cant_destroy") }
        format.turbo_stream do
          @successful_destroy = false
          flash.now[:warning] = t(".cant_destroy")
        end
      end
    end
  end

  # POST /accounts/:account_id/categories/import_from
  def import_from
    other_categories
    @other_categories.each do |other_category|
      next if current_categories.exists?(name: other_category.name)

      @category = current_categories.build
      @category.name   = other_category.name
      @category.hidden = other_category.hidden
      save_category
    end

    redirect_to account_categories_url(@current_account), notice: t(".successfully_imported")
  end

  private ##############################################################################################################

    def categories(options = {})
      @categories ||= current_categories.offset(options[:offset]).limit(options[:limit]).order_by_name
    end

    def load_other_accounts
      @other_accounts = @current_accounts.free_of(@current_account)
    end

    def category
      @category ||= current_categories.find(params[:id])
    end

    def other_categories
      @other_categories ||= @current_accounts.find(params[:categories]).categories
    end

    def build_category
      @category ||= current_categories.build
      @category.attributes = category_params
    end

    def category_params
      category_params = params[:category]
      category_params ? category_params.permit(:name, :hidden) : {}
    end

    def save_category
      return unless @category.save

      userstamp(@category)
    end

    def current_categories
      @current_account.categories
    end
end

app/views/categories/_category.html.erb
<% categories.each do |category| %>
  <tr class="<% 'has-text-grey-light' if category.hidden == true %>" id="<%= dom_id(category) %>">
    <%# name %>
    <td data-title="<%= name %>">
      <%= category.name %>
    </td>

    <%# count %>
    <td data-title="<%= use %>">
      <%= t(".time", total: category.transactions.active.count) %>
    </td>

    <%# common %>
    <td>
      <div class="level is-mobile">
        <div class="level-left">
          <div class="level-item has-text-centered">
            <%= link_to icon("fa-solid fa-pen-to-square"), edit_category_path(category), title: t(".edit"), class: "has-text-info" %>
          </div>
          <div class="level-item has-text-centered">
            <%= link_to icon("fa-regular fa-trash-can"),
                        category_path(category),
                        data: {  turbo_method: :delete, turbo_confirm: t(".are_you_sure", category: category.name) },
                        title: t(".destroy"),
                        class: "has-text-danger" %>
          </div>
          <% if category.hidden == true %>
            <div class="level-item has-text-centered">
              <%= tag.span(class: "icon") { tag.i class: "fa-regular fa-eye-slash", title: t(".hidden_category") } %>
            </div>
          <% end %>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: shallow_args(@current_account, @category), class: "box", data: { turbo: false }) do |form| %>
  <div class="content has-text-centered">
    <%= icon_text("fa-solid fa-tags", title) %>
    <hr />
  </div>

  <%# name %>
  <div class="field">
    <%= form.label :name, t(".name"), class: "label" %>
    <div class="control has-icons-left">
      <%= form.text_field :name, class: input_class_for(@category, :name), placeholder: t(".name") %>
      <span class="icon is-left">
        <%= icon("fa-solid fa-quote-left") %>
      </span>
      <% @category.errors.full_messages_for(:name).each do |message| %>
        <p class="help is-danger">
          <%= message %>
        </p>
      <% end %>
    </div>
  </div>

  <%# hidden %>
  <div class="field">
    <%= form.label :hidden, t(".hidden"), class: "checkbox" do %>
      <%= form.check_box :hidden %>
      <%= " " + t(".hidden") %>
    <% end %>
  </div>

  <%# submit button %>
  <div class="mt-5">
    <%= form.submit class: "button is-success is-fullwidth" %>
  </div>
<% end %>

app/views/categories/_import_from.html.erb
<div class="modal" data-action="keydown.esc@window->layout#hideModal" data-layout-target="modal">
  <div class="modal-background"></div>
  <%= form_with(url: :import_from_account_categories, method: :import_from) do |form| %>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title is-size-6-mobile">
          <%= t(".title") %>
        </p>
        <a class="delete" data-action="layout#hideModal"></a>
      </header>
      <section class="modal-card-body">
        <div class="field">
          <p class="help">
            <%= t(".speech").html_safe %>
          </p>
          <%= form.label t(".import_from"), class: "label" %>
          <div class="control has-icons-left">
            <div class="select">
              <%= form.collection_select :categories, @other_accounts, :id, :name %>
            </div>
            <div class="icon is-left">
              <%= icon("fa-solid fa-book") %>
            </div>
          </div>
        </div>
      </section>
    </div>
    <footer class="modal-card-foot">
      <div class="field">
        <div class="control">
          <%= form.submit class: "button is-primary" %>
        </div>
      </div>
    </footer>
  <% end %>
</div>

app/views/categories/_welcome.html.erb
<div class="modal is-active" data-action="keydown.esc@window->layout#hideModal" data-controller="layout" data-layout-target="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title is-size-6-mobile">
        <%= t(".welcome") %>
      </p>
      <button class="delete" data-action="layout#hideModal"></button>
    </header>
    <section class="modal-card-body">
      <div class="content">
        <%= t(".content", new_icon: icon("fa-solid fa-circle-plus"),
                          transactions_icon: icon("fa-regular fa-credit-card"),
                          schedules_icon: icon("fa-regular fa-calendar-days")).html_safe %>
      </div>
    </section>
    <footer class="modal-card-foot">
      <button class="button is-success" data-action="layout#hideModal">
        <%= t(".close") %>
      </button></footer>
  </div>
</div>

app/views/categories/destroy.turbo_stream.erb
<% if @successful_destroy %>
  <%# remove item in table %>
  <%= turbo_stream.remove @category %>

  <%# update total number of items %>
  <%= turbo_stream.replace "total", partial: "layouts/tag", locals: { title: t(".count"), number_of: @nb_categories } %>
<% end %>

<%# show flash message %>
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/categories/edit.html.erb
<%= breadcrumb link_to(@current_account.name, account_categories_path(@current_account)),
               link_to(t(".edit_category"), edit_category_path(@category)) %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".edit_category") } %>
  </div>
</div>

app/views/categories/index.html.erb
<%# welcome %>
<% unless @all_user_categories.any? %>
  <%= render "welcome" %>
<% end %>

<%# header %>
<div class="level">
  <%# title %>
  <div class="level-left">
    <div class="level-item">
      <h2 class="title">
        <%= t(".listing_categories", current_account: @current_account.name) %>
        <%= render partial: "layouts/tag", locals: { title: t('.count'), number_of: @nb_categories } %>
      </h2>
    </div>
  </div>
  
  <%# download %>
  <div class="level-right">
    <div class="level-item is-hidden-touch">
      <%= link_to icon("fa-solid fa-download"),
                  account_categories_path(@current_account, format: :xlsx),
                  title: t(".export_categories"),
                  class: "button is-link is-light" %>
    </div>

    <%# import categories from %>
    <% if @current_accounts.count > 1 %>
      <div class="level-item" data-controller="layout">
        <%= render "import_from" %>
        <%= button_tag icon_text("fa-solid fa-right-left", t(".import_from")),
                       class: "button is-link is-light is-outlined",
                       data: { action: "layout#showModal" } %>

      </div>
    <% end %>

    <%# new category %>
    <div class="level-item">
      <%= link_to icon_text("fa-solid fa-circle-plus", t(".new_category")), new_account_category_path, class: "button is-primary" %>
    </div>
  </div>
</div>

<%# table %>
<table class="table is-fullwidth is-striped" id="magic-table">
  <thead>
    <tr>
      <th>
        <%= t(".name") %>
      </th>
      <th>
        <%= t(".use") %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody id="listing">
    <%= render partial: "category", locals: { categories: @categories, name: t(".name"), use: t(".use") } %>
  </tbody>
</table>

<%# more categories %>
<% if @nb_categories > @limit %>
  <%= turbo_frame_tag "items", src: account_categories_path(@current_account, offset: @limit, format: :turbo_stream), loading: "lazy" %>
<% end %>

app/views/categories/index.turbo_stream.erb
<%= turbo_stream.append "listing", partial: "category", locals: { categories: @categories, name: t(".name"), use: t(".use") } %>

<% if @nb_categories > @nb_items %>
  <%= turbo_stream.replace "items" do %>
    <%= turbo_frame_tag "items", src: account_categories_path(@current_account, offset: @nb_items, format: :turbo_stream), loading: "lazy" %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "items" %>
<% end %>

app/views/categories/new.html.erb
<%= breadcrumb link_to(@current_account.name, account_categories_path(@current_account)),
               link_to(t(".create_category"), new_account_category_path) %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".create_category") } %>
  </div>
</div>