config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  controller :rights do
    get "terms"  => :terms
    get "cookie" => :cookie
    get "gdpr"   => :gdpr
  end

  controller :sessions do
    get    "login"  => :new
    post   "login"  => :create
    delete "logout" => :destroy
  end
  resources :passwords, param: :token, except: %i[ index show destroy ]

  shallow do
    resources :users, except: %i[index show] do
      resources :searches, except: %i[index edit update]
      resources :analytics, only: [ :index ]
    end
  end

  shallow do
    resources :accounts, except: [ :show ] do
      resources :categories, except: [ :show ] do
        post "import_from", on: :collection
      end
      resources :transactions, except: [ :show ] do
        post "easycheck", on: :member
      end
      resources :schedules, except: [ :show ] do
        post "insert", on: :member
      end
    end
  end

  delete "accounts/:id/unlink(.:format)",    to: "accounts#unlink",    as: "unlink"
  delete "accounts/:id/unpend(.:format)",    to: "accounts#unpend",    as: "unpend"
  post   "accounts/:id/sharing(.:format)",   to: "accounts#sharing",   as: "sharing"
  delete "accounts/:id/unsharing(.:format)", to: "accounts#unsharing", as: "unsharing"

  root "dashboard#index", as: "dashboard"
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  include SearchedTransactions
  before_action :set_current_account

  # GET /accounts/:account_id/transactions
  def index
    load_limit

    respond_to do |format|
      format.html do
        @all_user_transactions = Transaction.active.where(account: @current_accounts)
        @nb_transactions = current_transactions.size
        @sum_checked     = @current_account.initial_balance + current_transactions.checked.sum(:amount)
        transactions(limit: @limit)
      end
      format.turbo_stream do
        @nb_transactions = current_transactions.size
        @nb_items = params[:offset].to_i.abs + @limit
        transactions(offset: params[:offset].to_i.abs, limit: @limit)
      end
      format.xlsx do
        attributes_to_extract = %w[id account_id category_id date amount checked comment]
        send_data current_transactions.to_xlsx(attributes_to_extract, "transactions"),
                  filename: "#{I18n.t("transactions.new.transactions")}_#{timestamp_for_export}.xlsx",
                  type:     :xlsx
      end
    end
  end

  # GET /accounts/:account_id/transactions/new
  def new
    build_transaction
    @sign = "debit"
  end

  # GET /transactions/:id/edit
  def edit
    transaction

    @sign = @transaction.amount.negative? ? "debit" : "credit"
    @transaction.amount = @transaction.amount.abs
    flash[:search_id] = params[:search_id] unless params[:search_id].nil?
  end

  # POST /accounts/:account_id/transactions
  def create
    build_transaction
    if save_transaction
      redirect_to account_transactions_url(@current_account), notice: t(".successfully_created")
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /transactions/:id
  def update
    # TODO: credit transaction + error screen = debit transaction
    transaction
    build_transaction
    if save_transaction
      if flash[:search_id].nil?
        redirect_to account_transactions_url(@current_account), notice: t(".successfully_updated"), status: :see_other
      else
        redirect_to search_url(flash[:search_id]), notice: t(".successfully_updated")
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /transactions/:id
  def destroy
    transaction
    if params[:search_id].nil?
      # from transactions controller
      account = @transaction.account
      if @transaction.destroy
        respond_to do |format|
          format.html { redirect_to account_transactions_path(account), notice: t(".successfully_destroyed") }
          format.turbo_stream do
            @successful_destroy = true
            @nb_transactions = current_transactions.size
            flash.now[:notice] = t(".successfully_destroyed")
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to account_transactions_path(account), warning: t(".cant_destroy") }
          format.turbo_stream do
            @successful_destroy = false
            flash.now[:warning] = t(".cant_destroy")
          end
        end
      end
    else
      # from searches controller
      # TODO: definitely not the right paths
      if @transaction.destroy
        respond_to do |format|
          format.html { redirect_to search_path(@current_user), notice: t(".successfully_destroyed") }
          format.turbo_stream do
            @successful_destroy = true
            @search = @current_user.searches.find(params[:search_id])
            load_transactions
            @nb_transactions = @transactions.count
            @sum_transactions = @transactions.sum(:amount)
            flash.now[:notice] = t(".successfully_destroyed")
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to search_path(@current_user), warning: t(".cant_destroy") }
          format.turbo_stream do
            @successful_destroy = false
            flash.now[:warning] = t(".cant_destroy")
          end
        end
      end
    end
  end

  # POST /transactions/:id/easycheck
  def easycheck
    transaction
    account = @transaction.account
    @transaction.toggle :checked
    @transaction.updated_by = @current_user.id

    respond_to do |format|
      if @transaction.save
        @sum_checked = @current_account.initial_balance + current_transactions.checked.sum(:amount)
        format.html do
          redirect_to(account_transactions_path(account), notice: t(".successfully_checked"))
        end
        format.turbo_stream
      end
    end
  end

  private ##############################################################################################################

    def transactions(options = {})
      @transactions = current_transactions.with_balances_for(@current_account)
                                          .offset(options[:offset])
                                          .limit(options[:limit])
                                          .order_by_date_and_id_desc
    end

    def transaction
      @transaction ||= current_transactions.find(params[:id])
    end

    def build_transaction
      @transaction ||= current_transactions.build
      @transaction.attributes = transaction_params
    end

    def transaction_params
      transaction_params = params[:transaction]
      if transaction_params
        transaction_params.permit(:category_id, :date, :amount, :checked, :comment)
      else
        {}
      end
    end

    def save_transaction
      return unless @transaction.save

      @transaction.amount = params[:sign] == "credit" ? @transaction.amount.abs : (@transaction.amount.abs * -1)
      userstamp(@transaction)
    end

    def current_transactions
      @current_account.transactions.active
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  def is_upcomming?(transaction)
    "class=upcoming-transaction" if transaction.date > Time.zone.today
  end

  def decoration_according_to_(transaction)
    if (transaction.date > Time.zone.today) && (transaction.balance >= 0)
      "has-text-grey"
    elsif transaction.balance.negative?
      "has-text-danger"
    end
  end
end

app/views/transactions/_easycheck.html.erb
<%= link_to transaction.checked ? icon("fa-regular fa-square-check") : icon("fa-regular fa-square"),
            easycheck_transaction_path(transaction, search_id: params[:id]),
            data: { turbo_method: :post },
            title: t(".check_transaction"),
            id: "easycheck_#{transaction.id}",
            class: "link-success" %>

app/views/transactions/_form.html.erb
<%= form_with(model: shallow_args(@current_account, @transaction), class: "box", data: { turbo: false }) do |form| %>
  <div class="content has-text-centered">
    <%= icon_text("fa-regular fa-calendar-days", title) %>
    <hr />
  </div>

  <%# amount %>
  <div class="field">
    <%= form.label :amount, t(".amount"), class: "label" %>
    <div class="field has-addons">
      <div class="control">
        <div class="select">
          <%= select_tag :sign, options_for_select([[t(".debit"), "debit"], [t(".credit"), "credit"]], @sign) %>
        </div>
      </div>
      <div class="control is-expanded has-icons-right">
        <%= form.number_field :amount, class: input_class_for(@transaction, :amount), placeholder: t(".amount"), autofocus: true, step: 0.01 %>
        <span class="icon is-right">
          <%= t("number.currency.format.unit") %>
        </span>
        <% @transaction.errors.full_messages_for(:amount).each do |message| %>
          <p class="help is-danger">
            <%= message %>
          </p>
        <% end %>
      </div>
    </div>
  </div>

  <%# date %>
  <div class="field">
    <%= form.label :date, t(".date"), class: "label" %>
    <div class="control has-icons-left">
      <%= form.date_field :date, class: input_class_for(@transaction, :date), placeholder: t(".date"), value: @transaction.date.nil? ? Date.today : @transaction.date %>
      <span class="icon is-left">
        <%= icon("fa-regular fa-calendar-check") %>
      </span>
      <% @transaction.errors.full_messages_for(:date).each do |message| %>
        <p class="help is-danger">
          <%= message %>
        </p>
      <% end %>
    </div>
  </div>

  <%# category %>
  <div class="field">
    <%= form.label :category_id, t(".category"), class: "label" %>
    <div class="control is-expanded has-icons-left">
      <div class="select is-fullwidth">
        <%= form.select :category_id, @current_account.categories.active.order(:name).collect { |category| [category.name, category.id] } %>
      </div>
      <span class="icon is-left">
        <%= icon("fa-solid fa-tags") %>
      </span>
    </div>
  </div>

  <%# comment %>
  <div class="field">
    <%= form.label :comment, t(".comment"), class: "label" %>
    <div class="control">
      <%= form.text_area :comment, class: "textarea", placeholder: t(".comment"), rows: 3 %>
    </div>
  </div>

  <%# checked %>
  <div class="field">
    <%= form.label :checked, t(".checked"), class: "checkbox" do %>
      <%= form.check_box :checked %>
      <%= " " + t(".checked") %>
    <% end %>
  </div>

  <%# submit button %>
  <div class="mt-5">
    <%= form.submit class: "button is-success is-fullwidth" %>
  </div>
<% end %>

app/views/transactions/_sum_checked.html.erb
<div class="has-text-grey-light" id="sum_checked">
  <span>
    <%= t(".sum_checked") %>
  </span>
  <span class="nowrap">
    <%= number_to_currency(sum_checked) %>
  </span>
</div>

app/views/transactions/_transaction.html.erb
<% transactions.each do |transaction| %>
  <tr <%= is_upcomming?(transaction) %> id="<%= dom_id(transaction) %>">

    <%# check %>
    <td>
      <%= render partial: "easycheck", locals: { transaction: transaction } %>
    </td>

    <%# date %>
    <td data-title="<%= date %>" class="<%= decoration_according_to_(transaction) %>">
      <%= l(transaction.date) %>
    </td>

    <%# category %>
    <td data-title="<%= category %>" class="<%= decoration_according_to_(transaction) %>">
      <%= transaction.category.name %>
    </td>

    <%# debit %>
    <td class="nowrap <%= decoration_according_to_(transaction) %> has-text-right" data-title="<%= debit %>">
      <%= number_to_currency(transaction.amount) if transaction.amount < 0 %>
    </td>

    <%# credit %>
    <td class="nowrap <%= decoration_according_to_(transaction) %> has-text-right" data-title="<%= credit %>">
      <%= number_to_currency(transaction.amount) if transaction.amount >= 0 %>
    </td>

    <%# balance %>
    <td class="nowrap <%= decoration_according_to_(transaction) %> has-text-right" data-title="<%= balance %>">
      <%= number_to_currency(transaction.balance) %>
    </td>

    <%# comment %>
    <td data-title="<%= comment %>" class="<%= decoration_according_to_(transaction) %>">
      <%= truncate(transaction.comment, length: 30) %>
    </td>

    <%# common %>
    <td>
      <div class="level is-mobile">
        <div class="level-left">
          <div class="level-item has-text-centered">
            <%= link_to icon("fa-solid fa-pen-to-square"), edit_transaction_path(transaction), title: t(".edit"), class: "has-text-info" %>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <%= link_to icon("fa-regular fa-trash-can"),
                      transaction_path(transaction),
                      data: { turbo_method: :delete, turbo_confirm: t(".are_you_sure") },
                      title: t(".destroy"),
                      class: "has-text-danger" %>
        </div>
      </div>
    </td>
  </tr>
<% end %>

app/views/transactions/_welcome.html.erb
<div class="modal is-active" data-action="keydown.esc@window->layout#hideModal" data-controller="layout" data-layout-target="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title is-size-6-mobile">
        <%= t(".welcome") %>
      </p>
      <button class="delete" data-action="layout#hideModal"></button>
    </header>
    <section class="modal-card-body">
      <div class="content">
        <%= t(".content", new_icon: icon("fa-solid fa-circle-plus"),
                          square_icon: icon("fa-regular fa-square"),
                          check_square_icon: icon("fa-regular fa-square-check")).html_safe %>
      </div>
    </section>
    <footer class="modal-card-foot">
      <button class="button is-success" data-action="layout#hideModal">
        <%= t(".close") %>
      </button>
    </footer>
  </div>
</div>

app/views/transactions/destroy.turbo_stream.erb
<% if @successful_destroy %>
  <%# remove item in table %>
  <%= turbo_stream.remove @transaction %>
  <% if params[:search_id].nil? %>
    <%# update total number of items %>
    <%= turbo_stream.replace "total", partial: "layouts/tag", locals: { title: t(".count"), number_of: @nb_transactions } %>
  <% else %>
    <%# update amount and number of items %>
    <%= turbo_stream.replace "amount", partial: "searches/sums", locals: { id_name: "amount", number: number_to_currency(@sum_transactions) } %>
    <%= turbo_stream.replace "no", partial: "searches/sums", locals: { id_name: "no", number: @nb_transactions } %>
  <% end %>
<% end %>
<%# show flash message %>
<%= turbo_stream.replace "flash", partial: "layouts/flash" %>

app/views/transactions/easycheck.turbo_stream.erb
<%= turbo_stream.replace "sum_checked", partial: "sum_checked", locals:  { sum_checked: @sum_checked } %>
<%= turbo_stream.replace "easycheck_#{@transaction.id}", partial: "easycheck", locals:  { transaction: @transaction } %>

app/views/transactions/edit.html.erb
<% if params[:search_id] %>
  <%= breadcrumb link_to(t(".search"), new_user_search_path(@current_user)),
                 link_to(t(".current_search_number"), search_path(params[:search_id])),
                 link_to(t(".edit_transaction"), edit_transaction_path(@transaction)) %>
<% else %>
  <%= breadcrumb link_to(@current_account.name, account_transactions_path(@current_account)),
                 link_to(t(".edit_transaction"), edit_transaction_path(@transaction)) %>
<% end %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".edit_transaction") } %>
  </div>
</div>

app/views/transactions/index.html.erb
<%# welcome %>
<% unless @all_user_transactions.any? %>
  <%= render "welcome" %>
<% end %>

<%# header %>
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <div>
        <h2 class="title">
          <%= t(".listing_transactions", current_account: @current_account.name) %>
          <%= render partial: "layouts/tag", locals: { title: t('.count'), number_of: @nb_transactions } %>
        </h2>
        <div class="heading">
          <%= render partial: "sum_checked", locals: { sum_checked: @sum_checked } %>
        </div>
      </div>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item is-hidden-touch">
      <%= link_to icon("fa-solid fa-download"),
                  account_transactions_path(@current_account, format: :xlsx),
                  title: t(".export_transactions"),
                  class: "button is-link is-light" %>
    </div>
    <div class="level-item">
      <%= link_to icon_text("fa-solid fa-circle-plus", t(".new_transaction")), new_account_transaction_path, class: "button is-primary" %>
    </div>
    <div class="level-item is-hidden-desktop" data-controller="transactions">
      <%= label_tag do %>
        <%= checkbox_tag :hide_upcoming_transactions, data: { action: "transactions#toggleUpcoming" } %>
        <%= t(".hide_upcoming_transactions") %>
      <% end %>
    </div>
  </div>
</div>

<%# table %>
<table class="table is-fullwidth is-striped" id="magic-table">
  <thead>
    <tr>
      <th></th>
      <th>
        <%= t(".date") %>
      </th>
      <th>
        <%= t(".category") %>
      </th>
      <th class="has-text-right">
        <%= t(".debit") %>
      </th>
      <th class="has-text-right">
        <%= t(".credit") %>
      </th>
      <th class="has-text-right">
        <%= t(".balance") %>
      </th>
      <th>
        <%= t(".comment") %>
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody id="listing">
    <%= render partial: "transaction", locals: { transactions: @transactions,
                                                 checked:      t(".checked"),
                                                 date:         t(".date"),
                                                 category:     t(".category"),
                                                 debit:        t(".debit"),
                                                 credit:       t(".credit"),
                                                 balance:      t(".balance"),
                                                 comment:      t(".comment") } %>
  </tbody>
</table>

<%# more transactions %>
<% if @nb_transactions > @limit %>
  <%= turbo_frame_tag "items", src: account_transactions_path(@current_account, offset: @limit, format: :turbo_stream), loading: "lazy" %>
<% end %>

app/views/transactions/index.turbo_stream.erb
<%= turbo_stream.append "listing", partial: "transaction", locals: { transactions: @transactions,
                                                                     checked:      t(".checked"),
                                                                     date:         t(".date"),
                                                                     category:     t(".category"),
                                                                     debit:        t(".debit"),
                                                                     credit:       t(".credit"),
                                                                     balance:      t(".balance"),
                                                                     comment:      t(".comment") } %>
<% if @nb_transactions > @nb_items %>
  <%= turbo_stream.replace "items" do %>
    <%= turbo_frame_tag "items", src: account_transactions_path(@current_account, offset: @nb_items, format: :turbo_stream), loading: "lazy" %>
  <% end %>
<% else %>
  <%= turbo_stream.remove "items" %>
<% end %>

app/views/transactions/new.html.erb
<%= breadcrumb link_to(@current_account.name, account_transactions_path(@current_account)),
               link_to(t(".create_transaction"), new_account_transaction_path) %>
<div class="columns is-centered">
  <div class="column is-narrow">
    <%= render partial: "form", locals: { title: t(".create_transaction") } %>
  </div>
</div>