config/routes.rb
Rails.application.routes.draw do
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  controller :rights do
    get "terms"  => :terms
    get "cookie" => :cookie
    get "gdpr"   => :gdpr
  end

  controller :sessions do
    get    "login"  => :new
    post   "login"  => :create
    delete "logout" => :destroy
  end
  resources :passwords, param: :token, except: %i[ index show destroy ]

  shallow do
    resources :users, except: %i[index show] do
      resources :searches, except: %i[index edit update]
      resources :analytics, only: [ :index ]
    end
  end

  shallow do
    resources :accounts, except: [ :show ] do
      resources :categories, except: [ :show ] do
        post "import_from", on: :collection
      end
      resources :transactions, except: [ :show ] do
        post "easycheck", on: :member
      end
      resources :schedules, except: [ :show ] do
        post "insert", on: :member
      end
    end
  end

  delete "accounts/:id/unlink(.:format)",    to: "accounts#unlink",    as: "unlink"
  delete "accounts/:id/unpend(.:format)",    to: "accounts#unpend",    as: "unpend"
  post   "accounts/:id/sharing(.:format)",   to: "accounts#sharing",   as: "sharing"
  delete "accounts/:id/unsharing(.:format)", to: "accounts#unsharing", as: "unsharing"

  root "dashboard#index", as: "dashboard"
end

app/views/layouts/_categories_menu.html.erb
<div id="categories-menu" class="navbar-item has-dropdown is-hoverable">
  <a class="navbar-link">
    <%= icon_text("fa-solid fa-tags", t(".categories")) %>
  </a>
  <div class="navbar-dropdown">
    <% @current_accounts.each do |account| %>
      <%= link_to account.name, account_categories_path(account), class: "navbar-item", id: dom_id(account, :menu) %>
    <% end %>
  </div>
</div>

app/views/layouts/_favicon.html.erb
<%= favicon_link_tag "apple-touch-icon.png", rel: "apple-touch-icon", sizes: "180x180" %>
<%= favicon_link_tag "favicon-32x32.png", rel: "icon", type: "image/png", sizes: "32x32" %>
<%= favicon_link_tag "favicon-16x16.png", rel: "icon", type: "image/png", sizes: "16x16" %>
<%= favicon_link_tag "safari-pinned-tab.svg", rel: "mask-icon", color: "#AB1A67" %>
<%= favicon_link_tag "favicon.ico", rel: "shortcut icon", type: "image/x-icon" %>

app/views/layouts/_flash.html.erb
<div id="flash">
  <% if flash[:alert] %>
    <section class="section pt-5 pb-0" data-controller="layout">
      <div class="container">
        <div class="notification is-danger is-light">
          <button aria-label="<%= t(".aria_close") %>" class="delete" data-action="layout#removeMessageBox"></button>
          <%= flash[:alert] %>
        </div>
      </div>
    </section>
  <% elsif flash[:warning] %>
    <section class="section pt-5 pb-0" data-controller="layout">
      <div class="container">
        <div class="notification is-warning is-light">
          <button aria-label="<%= t(".aria_close") %>" class="delete" data-action="layout#removeMessageBox"></button>
          <%= flash[:warning] %>
        </div>
      </div>
    </section>
  <% elsif flash[:notice] %>
    <section class="section pt-5 pb-0" data-controller="layout">
      <div class="container">
        <div class="notification is-success is-light">
          <button aria-label="<%= t(".aria_close") %>" class="delete" data-action="layout#removeMessageBox"></button>
          <%= flash[:notice] %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/layouts/_tag.html.erb
<sup id="total" title="<%= title %>">
  <div class="tag is-primary is-rounded">
    <%= number_of %>
  </div>
</sup>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale.to_s.gsub('_','-') %>">
  <head>
    <meta charset="utf-8" />
    <title>Smoothie Funds<%= " - DEV" if Rails.env.development? %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <%= render partial: "layouts/favicon" %>
    <meta content="Thomas JUSTINO" name="author" />
    <meta content="<%= t('.site_descritpion') %>" name="description" />
    <meta content="SmoothieFunds" property="og:title" />
    <meta content="<%= t('.site_descritpion') %>" property="og:description" />
    <meta content="<%= I18n.locale.to_s %>" property="og:locale" />
    <meta content="website" property="og:type" />
    <meta content="<%= dashboard_url %>" property="og:url" />
    <meta content="<%= asset_url('_icon.svg') %>" property="og:image" />
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @current_user %>
      <%# Static navbar %>
      <nav aria-label="main navigation" class="navbar is-transparent" data-controller="layout" role="navigation">
        <div class="container">
          <%# brand %>
          <div class="navbar-brand">
            <%= link_to dashboard_path, class: "navbar-item" do %>
              <%= image_tag "_icon.svg", alt: "🥤" %>
            <% end %>
            <%# burger menu %>
            <a aria-expanded="false" aria-label="menu" class="navbar-burger" data-action="layout#toggleMenu" data-layout-target="navBarBurger" role="button">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>
          <%# navigation %>
          <div class="navbar-menu" data-layout-target="navBarMenu">
            <%# left part %>
            <div class="navbar-start">
              <% if Category.exists?(account: @current_accounts) %>
                <%# transactions %>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                    <%= icon_text("fa-regular fa-credit-card", t(".transactions")) %>
                  </a>
                  <div class="navbar-dropdown">
                    <% @accounts_with_categories.each do |account| %>
                      <%= link_to account.name, account_transactions_path(account), class: "navbar-item" %>
                    <% end %>
                    <hr class="navbar-divider" />
                    <%= link_to icon_text_light("fa-solid fa-magnifying-glass", t(".search")), new_user_search_path(@current_user), class: "navbar-item icon-text" %>
                    <%= link_to icon_text_light("fa-solid fa-chart-area", t(".analytics")), user_analytics_path(@current_user), class: "navbar-item icon-text" %>
                  </div>
                </div>
                <%# schedules %>
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link">
                    <%= icon_text("fa-regular fa-calendar-days", t(".schedules")) %>
                  </a>
                  <div class="navbar-dropdown">
                    <% @accounts_with_categories.each do |account| %>
                      <%= link_to account.name, account_schedules_path(account), class: "navbar-item" %>
                    <% end %>
                  </div>
                </div>
              <% end %>
              <%# categories %>
              <% if @current_accounts.any? %>
                <%= render partial: "layouts/categories_menu" %>
              <% end %>
              <%# accounts %>
              <%= link_to icon_text("fa-solid fa-book", t(".accounts")), accounts_path, class: "navbar-item" %>
            </div>

            <%# right part %>
            <div class="navbar-end">
              <%# user account %>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link">
                  <%= icon_text "fa-solid fa-user", name_or_email(@current_user) %>
                </a>
                <div class="navbar-dropdown">
                  <%# profil %>
                  <%= link_to icon_text_light("fa-solid fa-sliders", t(".profile")), edit_user_path(@current_user), class: "navbar-item icon-text" %>
                  <%= mail_to "support@smoothiefunds.com", icon_text_light("fa-solid fa-headset", t(".support")), class: "navbar-item icon-text" %>
                  <hr class="navbar-divider" />
                  <%# logout %>
                  <%= link_to icon_text_light("fa-solid fa-power-off", t(".logout")), logout_path, data: { turbo_method: :delete }, id: "logout", class: "navbar-item icon-text" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </nav>
    <% end %>

    <%# flash %>
    <%= render partial: "layouts/flash" %>

    <%# content %>
    <div id="wrapper">
      <noscript>
        <div class="message is-danger">
          <div class="message-body">
            <%= t(".alert_no_js") %>
          </div>
        </div>
      </noscript>
      <section class="section pt-5">
        <div class="container">
          <%= yield %>
        </div>
      </section>
    </div>

    <%# footer %>
    <footer class="footer sticky">
      <div class="container">
        <div class="columns is-centered">
          <div class="column mb-0 is-2 content is-small has-text-centered">
            <%= link_to t(".terms_of_use"),  terms_path %>
          </div>
          <div class="column mb-0 is-2 content is-small has-text-centered">
            <%= link_to t(".cookie_policy"), cookie_path %>
          </div>
          <div class="column mb-0 is-2 content is-small has-text-centered">
            <%= link_to t(".personal_data"), gdpr_path %>
          </div>
        </div>
      </div>
    </footer>

    <%# debugger %>
    <% if Rails.env.development? %>
      <div class="columns" id="debugBox" style="position:fixed;bottom:0;right:0;">
        <div class="column is-narrow mr-1 mb-1 is-hidden-mobile">
          <section class="message is-warning is-small is-narrow" data-controller="layout">
            <div class="message-header">
              <p>Debug</p>
              <button aria-label="<%= t(".aria_close") %>" class="delete" data-action="layout#removeMessageBox"></button>
            </div>
            <div class="message-body">
              <%= debug(request.parameters) %>
            </div>
          </section>
        </div>
      </div>
    <% end %>
  </body>
</html>